#
# This package acquires the current, daily, hourly, and alerts data from OpenWeatherMap using the one-call-by-call API
# Then, current, daily and hourly entities are created for most of the provided metrics
#
sensor:
  - platform: rest
    name: openweather_report
    # remove any attributes you do not want in your report.  You can also add the deleted ones to the "exclude" list in the api call below. Note, this has not been tested.
    json_attributes:
      - current
      - daily
      - hourly
      - alerts
    value_template: "{{ value_json['current']['dt'] | timestamp_custom('%Y-%m-%d %H:%M', true) }}"
    # Replace <xxx> with your Lat, Lon, and API key.  Chage units to metric if desired, and lang as well
    resource: https://api.openweathermap.org/data/3.0/onecall?lat=<Your_Lat>&lon=<Your_Lon>&exclude=minutely&appid=<Your_ONE_CALL_API_KEY>&units=imperial&lang=en
    # make sure that all sources makeing API calls using your API_KEY do not exceed the ONE_CALL limit unless you want to pay for more frequent updates.
    scan_interval: 3600
#
# Daily and hourly sensors are added below by the createopenweather script
